version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-25-alpha
  working_directory: ~/repo
  environment:
    _JAVA_OPTIONS: "-Xmx2048m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Copy Environment Variables
          command: source .circleci/creategradleproperties.sh && copyEnvVarsToGradleProperties
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Clean
          command: ./gradlew clean
      - run:
          name: Run tests on views module
          command: ./gradlew :views:testReleaseUnitTest
      - run:
          name: Run tests on app module
          command: ./gradlew :app:testProdReleaseUnitTest
      - run:
          name: Assemble APKs
          command: ./gradlew :app:assembleRelease
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/reports
          destination: reports/app
      - store_artifacts:
          path: views/build/reports
          destination: reports/views
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: views/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - build
            - app/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
